demo_app/config/routes.rb
DemoApp::Application.routes.draw do
  resources :sessions, :only=>[:new,:create,:destroy]
  match '/signin',:to=>'sessions#new'
  match '/signout',:to=>'sessions#destroy'

  root :to => 'pages#home'
  match '/contact',:to =>'pages#contact'
  match '/about',:to =>'pages#about'
  match '/help',:to =>'pages#help'
  match '/signup',:to =>'users#new'
  resources :users

end

demo_app/app/models/user.rb
require 'digest'
class User < ActiveRecord::Base

  attr_accessor :password
  attr_accessible :email, :name ,:password,:password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z+\d\-.]+\.[a-z]+\z/i

  validates :name, :presence=>true, :length=> { :maximum=>50 }

  validates :email, :presence=>true, :format=>   {:with=>email_regex}, :uniqueness=>{:case_sensitive=>false }
             validates :password, :presence=>true, :confirmation=>true,  
:length => {:within=> 6..40}

before_save :do_encrypt_password
 def has_password?(submitted_password)
 encrypt_password==encrypt(submitted_password)
 end
 
def self.authenticate(email,submitted_password)
    user= find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
    return nil
end

 private
 def do_encrypt_password
     self.encrypt_password = encrypt(password)
 end 
 
def encrypt(string)
  Digest::SHA2.hexdigest(string)
end
end

demo_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

demo_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title="Home"
  end

  def about
    @title="about"
  end

 def help
    @title="help"
  end

  def contact
    @title="contact"
  end
end

demo_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@title = "Sign In"
		end
	def create
	 	user=User.authenticate(params[:session][:email],params[:session][:password])
		if user.nil?
			flash.now[:error] = "invalid email or password"
			@title="Sign In"
			render "new"
		else 
                    sign_in user
                    redirect_to user
		end
	end
	def destroy
            sign_out 
            redirect_to root_path
	end
end

demo_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only=> [:edit,:update,:destroy]
  private 

  def authenticate
    if current_user.nil?
      redirect_to signin_path,:notice => "please sign in"
    else
      user=User.find(params[:id])
      if user != current_user
        redirect_to root_path,
          :notice=>"editing other user is not allowed"
      end
     end
  end

public
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end

  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])


      if @user.save
                sign_in @user
                redirect_to @user
      else
               @title =  "Sign up"
               render "new"

      end
       
    end


  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

demo_app/app/helpers/application_helper.rb
module ApplicationHelper
end

demo_app/app/helpers/pages_helper.rb
module PagesHelper
end

demo_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

demo_app/app/helpers/users_helper.rb
module UsersHelper
end

demo_app/app/views/layouts/_footer.html.erb
<footer>
<nav class="round">
<ul>
<li><%=link_to "About", about_path%></li>
<li><%=link_to "Contact", contact_path%></li>
<li><a href="">News</a></li>
<li><a href="">Rails Tutorial</a></li>		
</ul>
</nav>
</footer>

demo_app/app/views/layouts/_header.html.erb
<header>
     <%=image_tag("logo.png",:alt=>"Sample App",:class=>"round")%>
     <nav class="round">
	<ul>
   	  <li><%=link_to "Home", root_path%></li>
	  <li><%=link_to "Help", help_path %></li>
          <% if current_user.nil? %>
	  <li><%=link_to "Sign In", signin_path %></li>
          <% else %>
         <li><%=link_to "Sign out", signout_path, :method=>:delete %></li>
         <% end %>
	</ul>    
     </nav>
</header>

demo_app/app/views/layouts/_stylesheet.html.erb
<header>
     <%=image_tag("logo.png",:alt=>"Sample App",:class=>"round")%>
    
</header>

demo_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby on Rails|<%=@title %></title>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>

 <%= stylesheet_link_tag 'blueprint/screen', :media =>'screen' %>
 <%= stylesheet_link_tag 'blueprint/print', :media =>'print'%>
 <%= stylesheet_link_tag 'custom', :media =>'screen'%>
</head>
<body>
<div class="container">
  <%= render 'layouts/header'%>

  <section class="round">
    <% flash.each do |key,value| %>
    <div class = "flash <%= key %>"><%= value %></div>
    <% end %>
     <%=yield %>
  </section>
  <%= render 'layouts/footer'%>
  <%= debug(params) if Rails.env.development?%>
<%= debug(cookies) if Rails.env.development?%>
<%= debug(current_user) if Rails.env.development?%>
</div>
</body>
</html>

demo_app/app/views/pages/about.html.erb
<DOCTYPE html>
<html>
<head>
<title>Ruby on Rails Tutorial Sample App| <%= @title %></title>
</head>
<body>
<h1>Sample App</h1>
<p>This is the home page for <a href="http://railstutorial.org">Ruby on Rails Tutorial</a> Sample App</p>
</body>
<html>

demo_app/app/views/pages/contact.html.erb
<DOCTYPE html>
<html>
<head>
<title>Ruby on Rails Tutorial Sample App| <%= @title %></title>
</head>
<body>
<h1>Sample App</h1>
<p>Contact Ruby On Rails Tutorial about the sample <a href="http://railstutorial.org">Ruby on Rails Tutorial</a> Sample App</p>
</body>
<html>

demo_app/app/views/pages/help.html .erb
<DOCTYPE html>
<html>
<head>
<title>Ruby on Rails Tutorial Sample App| <%= @title %></title>
</head>
<body>
<h1>Sample App</h1>
<p>This is the home page for <a href="http://railstutorial.org">Ruby on Rails Tutorial</a> Sample App</p>
</body>
<html>

demo_app/app/views/pages/help.html.erb
<DOCTYPE html>
<html>
<head>
<title>Ruby on Rails Tutorial Sample App| <%= @title %></title>
</head>
<body>
<h1>Sample App</h1>
<p>This is the home page for <a href="http://railstutorial.org">Ruby on Rails Tutorial</a> Sample App</p>
</body>
<html>

demo_app/app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>This is the home page for
 <a href="http://railstutorial.org">Ruby on Rails Tutorial</a> Sample App
</p>
<%=link_to "Sign up now!",signup_path,:class=>"signup_button round" %>
<%=link_to "show all user", users_path %>

demo_app/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo_app/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

demo_app/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

demo_app/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

demo_app/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>